name       : python3-ezsetup
version    : 0.9
release    : 1
source     :
    - https://pypi.python.org/packages/source/e/ez_setup/ez_setup-0.9.tar.gz : 303c5b17d552d1e3fb0505d80549f8579f557e13d8dc90e5ecef3c07d7f58642
license    : MIT
summary    : Python ez_setup
description: |
    Python ez_setup
builddeps  :
    - python3-setuptools
    - python3-devel
setup      : |
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --root=%installroot% --no-compile -O0
